---
title: "aqua"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{aqua}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(mbtransfer)
library(tidyverse)
library(glue)
th <- theme_bw() +
  theme(
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_rect(fill = NA, color = "#0c0c0c", size = 0.6),
    axis.text = element_text(size = 8),
    axis.title = element_text(size = 12),
    legend.position = "bottom"
  )
theme_set(th)
```

```{r}
reads <- read_csv("https://figshare.com/ndownloader/files/40357894/reads.csv") |>
  column_to_rownames("sample")
samples <- read_csv("https://figshare.com/ndownloader/files/40357897/samples.csv")
subject <- read_csv("https://figshare.com/ndownloader/files/40357891/subject.csv")
interventions <- read_csv("https://figshare.com/ndownloader/files/40357888/interventions.csv") |>
  column_to_rownames("sample")
```

```{r}
ts <- reads |>
  ts_from_dfs(interventions, samples, subject) |>
  interpolate(method = "linear")

ts <- ts[1:3]
```

```{r}
ts_missing <- subset_values(ts, 1:96)
fit <- mbtransfer(ts, P = 3, Q = 3)
ts_pred <- predict(fit, ts_missing)
```

```{r}
ws <- steps(c("pH" = TRUE, "AS" = FALSE), lengths = 4, L = 4) |>
  map(~ 2 * . + 5)
ws[[1]]["AS", ] <- 38
ws[[2]]["AS", ] <- 38

#staxa <- select_taxa(ts[1:3], ws[[1]], ws[[2]], \(x) mbtransfer(x, 3, 3), n_splits = 20)
#save(staxa, file = "../../data/staxa-aqua.rds")
staxa <- readRDS("../../data/staxa-aqua.rds")
```

Maybe show a gradually increasing trajectory?
or better - several increasing trajectories.

```{r, fig.height = 5, fig.width = 10}
vis_otus <- staxa$ms |>
  group_by(taxon) |>
  summarise(m = mean(m)) |>
  slice_max(m, n = 50) |>
  pull(taxon)

staxa$ms |>
  filter(taxon %in% vis_otus) |>
  mutate(
    taxon = taxa(ts)[taxon],
    lag = as.factor(lag),
    selected = ifelse(taxon %in% unlist(staxa$taxa), "Selected", "Unselected")
  ) |>
  ggplot() +
  geom_hline(yintercept = 0, linewidth = 2, col = "#d3d3d3") +
  geom_boxplot(aes(reorder(taxon, -m), m, fill = lag, col = lag), alpha = 0.8) +
  facet_grid(. ~ selected, scales = "free_x", space = "free_x") +
  scale_fill_manual(values = c("#c6dbef", "#6baed6", "#2171b5", "#084594")) +
  scale_color_manual(values = c("#c6dbef", "#6baed6", "#2171b5", "#084594")) +
  labs(y = expression(M[j]), x = "Taxon") +
  theme(axis.text.x = element_text(angle = 90, size = 11))
```

This simulates different lengths of pH interventions, starting at 5 and
gradually increasing to 9.

```{r}
L <- 42
ws <- list()
plateaus <- seq(3, 9, length.out = 4)
for (p in seq_along(plateaus)) {
  ws[[p]] <- matrix(38, nrow = 2, ncol = L)
  colnames(ws[[p]]) <- glue("t{seq_len(L)}")
  rownames(ws[[p]]) <- c("pH", "AS")
  ws[[p]][1, ] <- rep(plateaus[p], L)
}
```

```{r}
focus_taxa <- unlist(map(staxa$taxa, ~ c(.)))
ts_df <- pivot_ts(ts)

taxa_order <- staxa$ms |>
  group_by(taxon) |>
  summarise(median_m = median(m)) |>
  arrange(-median_m) |>
  pull(taxon)

ts_df |>
  mutate(taxon = factor(taxon, levels = taxa(ts)[taxa_order])) |>
  filter(taxon %in% focus_taxa, taxon %in% taxa(ts)[vis_otus]) |>
  ggplot() +
  geom_point(aes(pH, value), alpha = 0.6, size = 0.8) +
  facet_wrap(~ taxon)
```

So far, we've selected using only a contrast in one of the two counterfactual
series. How do the trajectories vary if we use differentially graded pH
interventions?

```{r}
sim_ts_ <- list()
for (i in seq_along(ws)) {
  sim_ts_[[i]] <- counterfactual_ts(ts, ws[[i]], ws[[i]], start_ix = 42)$ts1
}
```

```{r}
pal <- c("#cbd8e8", "#becbdc", "#b1bed0", "#a4b2c4", "#97a5b8", "#8b99ac", "#808da0", "#748193", "#697587", "#5e697b")

sim_ts <- map(sim_ts_, ~ predict(fit, .)) |>
  map_dfr(sim_ts, pivot_ts, .id = "counterfactual")

sim_ts |>
  filter(taxon %in% focus_taxa, time > 40, time < 70) |>
  mutate(
    pH = factor(plateaus[as.integer(counterfactual)]),
    taxon = factor(taxon, levels = taxa(ts)[taxa_order])
    ) |>
  group_by(taxon, time, pH) |>
  summarise(
    q25 = quantile(value, 0.25),
    q50 = median(value),
    q75 = quantile(value, 0.75),
  ) |>
  ggplot() +
   geom_ribbon(aes(time, ymin = q25, ymax = q75, fill = pH)) +
   facet_wrap(~ taxon, ncol = 6) +
   scale_fill_manual(values = pal)
```

