---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
library(phyloseq)
library(glue)
library(fs)
library(mbtransfer)
library(tfPaper)
library(tidyverse)
theme_set(my_theme())
```

```{r}
read_fun <- function(x) {
  if(str_detect(x, "rds")) {
    return (readRDS(x))
  }
  read_tsv(x)
}

data_dir <- path("../data/aqua")
aqua_data <- dir_map(data_dir, read_fun)
```

First, we reshape and impute the eel activity data.


```{r}
tank_data <- aqua_data[[1]] |>
  pivot_longer(-Day) |>
  separate(name, c("tank", "variable")) |>
  arrange(tank, variable, Day)

for (i in seq_len(nrow(tank_data))) {
  if (is.na(tank_data$value[i])) {
    tank_data$value[i] <- tank_data$value[i - 1]
  }
}

tank_data <- tank_data |>
  pivot_wider(names_from = variable, values_from = value)
```

Next, we aggregate to the taxon level.

```{r}
x <- otu_table(aqua_data[[4]], taxa_are_rows = FALSE)
z <- aqua_data[[2]] |>
  filter(Sample.ID %in% rownames(x)) |>
  mutate(sample = rownames(x)) |>
  column_to_rownames("sample") |>
  sample_data()
tax_tab <- tax_table(aqua_data[[3]][, -1])
taxa_names(tax_tab) <- colnames(x)

ps <- phyloseq(x, z, tax_tab) |>
  tax_glom(taxrank = "ta7")
```
```{r}
prevalent <- colMeans(otu_table(ps) > 0) > 0.4
prevalent <- names(prevalent[which(prevalent)])
ps <- prune_taxa(prevalent, ps)
```

```{r, fig.height = 8, fig.width = 4}
interventions |>
  rownames_to_column("sample") |>
  left_join(samples) |>
  left_join(rownames_to_column(data.frame(reads[, 1:11]), "sample")) |>
  pivot_longer(starts_with("X_"), names_to = "taxon") |>
  ggplot() +
  geom_point(aes(asinh(value), pH, col = subject)) +
  facet_grid(taxon ~ subject)

interventions |>
  rownames_to_column("sample") |>
  left_join(samples) |>
  left_join(rownames_to_column(data.frame(reads[, 1:11]), "sample")) |>
  ggplot() +
  geom_line(aes(time, asinh(X_0010), group = subject)) +
  geom_line(aes(time, pH, group = subject), col = "red")
```

```{r}
reads <- otu_table(ps)
samples <- sample_data(ps) |>
  as_tibble() |>
  rename(
    "sample" = "Sample.ID",
    "subject" = "Tank",
    "time" = "Day"
    ) |>
  mutate(subject = glue("T{subject}"))

subject <- samples |>
  as_tibble() |>
  select(subject) |>
  distinct() |>
  mutate(id = seq_len(n()))

interventions <- samples |>
  left_join(tank_data, by = c("time" = "Day", "subject" = "tank")) |>
  column_to_rownames("sample") |>
  select(pH, AS)
```

```{r}
write_csv(samples, out_dir / "samples.csv")
write_csv(reads, out_dir / "reads.csv")
write_csv(subject, out_dir / "subject.csv")
write_csv(interventions, out_dir / "interventions.csv")
```


```{r}
ts <- reads |>
  normalize("DESeq2-asinh", samples) |>
  ts_from_dfs(interventions, samples, subject) |>
  interpolate(method = "linear")

#saveRDS(ts, "../data/ts-aqua.rds")
```

```{r, eval=F}
ts_missing <- subset_values(ts, 1:8)
fit <- mbtransfer(ts, P = 3, Q = 3)
ts_pred <- predict(fit, ts_missing)
```

```{r}
ws <- steps(c("pH" = TRUE, "AS" = FALSE), lengths = 4, L = 4) |>
  map(~ 2 * . + 5)
ws[[1]]["AS", ] <- 38
ws[[2]]["AS", ] <- 38

staxa <- select_taxa(ts[1:3], ws[[1]], ws[[2]], \(x) mbtransfer(x, 3, 3), n_splits = 20)
save(staxa, file = "../data/staxa-aqua.rds")
#staxa <- readRDS("../data/staxa-diet.rds")
```

Maybe show a gradually increasing trajectory?
or better - several increasing trajectories.

```{r}
fit <- tr_fun(ts)
ws <- steps(c("AS" = TRUE, "pH" = FALSE), lengths = 7, L = 21) |>
  map(~ 20 * . + 20)
ws[[1]]["pH", ] <- 6.2
ws[[2]]["pH", ] <- 6.2

# sim_ts <- counterfactual_ts(ts, ws[[1]], ws[[2]], start_ix = 64) |>
#   map(~ predict(fit, .))
```
