---
title: "Untitled"
output: 
  html_document:
    highlight: "kate"
params:
  outputs_dir: "/Users/krissankaran/Desktop/collaborations/microbiome_interventions/data/tf_sim"
  outputs_filter: "*rda"
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
params <- list(outputs_dir = "/Users/krissankaran/Desktop/collaborations/microbiome_interventions/data/tf_sim", outputs_filter = "*rda")
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(fido2)
library(fs)
library(glue)
library(mdsine)
library(mbtransfer)
library(tfPaper)
library(tidyverse)
theme_set(my_theme())
reticulate::use_condaenv("/opt/miniconda3/envs/mdsine/")
```

Comparison in MDSINE vs. mbtransfer predictions.

```{r}
paths <- dir_ls(params$outputs_dir, recurse = TRUE) |>
  path_filter(regexp=params$outputs_filter)

load(paths[str_detect(paths, "sim_input_099")])
interventions_df <- data.frame(interventions) |>
  rownames_to_column("sample")
metadata <- metadata |>
  left_join(interventions_df) |>
  rename(condition = P1)
reads[reads > .Machine$integer.max] <- .Machine$integer.max - 1

ts <- reads |>
  normalize("none", metadata) |>
  ts_from_dfs(interventions, metadata, subject_data) |>
  interpolate()
```

```{r configurations}
configurations <- str_detect(paths, "sim_input") |>
  path_abs() |>
  method_configurations() |>
  mutate(data_path_base = basename(as.character(data_path)))

data_config <- data_parameters() |>
  mutate(data_path_base = basename(output_path)) |>
  select(-output_path)

configurations <- configurations |>
  left_join(data_config) |>
  filter(!(method == "mdsine" & n_taxa > 200))
```

```{r}
cvs <- list()
#predict <- mdsine::predict
#cvs[["mdsine"]] <- cross_validate(ts, \(x) mdsine(x, taxonomy), K = 4, seeds = 1:4)
predict <- mbtransfer::predict
cvs[["mbtransfer"]] <- cross_validate(ts, \(x) mbtransfer(x, 2, 2), K = 4, seeds = 1:4)
predict <- fido2::predict
cvs[["fido"]] <- cross_validate(ts, \(x) fido(x, sigma = 1, rho = 1), K = 4, seeds = 1:4)
saveRDS(cvs, "data/compare-trajectories.rds")
#cvs <- readRDS("../data/compare-trajectories.rds")
```

### Visualize the Differences

```{r}
metrics <- map_dfr(cvs, ~ .$metrics, .id =  "method")

ggplot(metrics) +
  geom_boxplot(aes(lag, fill = method, col = method, mae), alpha = 0.6)
```

```{r}
metrics |>
  group_by(method) |>
  slice_max(mae, n = 5)

metrics |>
  group_by(method) |>
  slice_min(mae, n = 5)
```

```{r}
for (i in seq_along(cvs[["mdsine"]]$y_hat)) {
  subject_data(cvs[["mdsine"]]$y_hat[[i]]) <-  tibble(
    subject  = names(cvs[["mdsine"]]$y_hat[[i]])
  )
}

cvs[["fido"]]$y_hat <- map(cvs[["fido"]]$y_hat, ~ {
  subject_ids <- list()
  for (i in seq_along(.)) {
    subject_ids[[i]] <- colnames(values(.[[i]]))
  }
  subject_ids <- str_extract(c(unlist(subject_ids)), "[0-9]+") |>
    unique()
  
  names(.) <- glue("S{subject_ids}")
  subject_data(.)$subject <- glue("S{subject_ids}")
  .
})

y_hats <- list(
  "mdsine" = map_dfr(cvs[["mdsine"]]$y_hat, ~ pivot_ts(.), .id = "fold"),
  "mbtransfer" = map_dfr(cvs[["mbtransfer"]]$y_hat, ~ pivot_ts(.), .id = "fold"),
  "fido" = map_dfr(cvs[["fido"]]$y_hat, ~ pivot_ts(.), .id = "fold")
) |>
  bind_rows(.id = "method")
```


```{r}
differenced_data <- y_hats |>
  left_join(pivot_ts(ts) |> rename(truth = value) |> select(-V1)) |> 
  mutate(
    difference = value - truth,
    difference = ifelse(difference > 50, 50, difference),
    difference = ifelse(difference < -50, -50, difference)
  )

differenced_data <- differenced_data |>
  group_by(sample) |>
  mutate(
    any_zero = any(difference == 0),
    difference = ifelse(any_zero, 0, difference),
    method = case_match(method, "mdsine" ~ "MDSINE2", "fido" ~ "fido", "mbtransfer" ~ "mbtransfer")
  )
```

```{r, fig.width = 12, fig.height = 6.5}
ggplot(differenced_data) +
  geom_tile(aes(time, subject, fill = difference, color = difference)) +
  scale_fill_gradient2(low = "#048ABF", mid = "white", high = "#F27405")  +
  scale_color_gradient2(low = "#048ABF", mid = "white", high = "#F27405")  +
  facet_grid(fold ~ method, scales = "free_y") +
  scale_x_continuous(limits = c(-8, 12), expand = c(0, 0)) +
  theme(
    axis.text.y = element_text(size = 5),
    panel.grid = element_blank(),
    strip.text = element_text(size = 12),
    panel.spacing.y = unit(0.1, "line"),
    panel.background = element_rect(fill = "#d3d3d3")
  )
ggsave("differenced_data.png", height = 4.5, width = 12)
```