---
title: "dlm"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(cmdstanr)
library(microTF)
set.seed(20230215)

n_timepoints <- 100
n_interventions <- 4

interventions <- matrix(0, n_interventions, n_timepoints)
interventions[1, c(10:40)] <- 1
interventions[2, c(50:70)] <- 1
interventions[3, c(50:60)] <- 1
interventions[4, c(80:90)] <- 1

res <- dlm_ensemble(interventions, 2, sigma_a = 0.4, sigma_b = 0.4, sigma_e = 0.1, sigma_z = 0.2, P = 2, Q = 2)
plot(res$x[[1]]@values[1, ])
plot(res$x[[1]]@values[2, ])
plot(res$z[[1]][1, ])
plot(res$z[[1]][2, ])

heatmap(res$x[[1]]@values)
heatmap(res$x[[2]]@values)
```

```{r}
model <- cmdstan_model("dlm.stan")
data_list <- list(
  x = res$x[[1]]@values,
  interventions = interventions,
  P = length(res$params$A),
  Q = length(res$params$B),
  K = nrow(res$z[[1]]),
  D = n_interventions,
  N = n_timepoints,
  V = nrow(res$x[[1]])
)

fit <- model$variational(data_list)
```

```{r}
z_post <- fit$draws("z") %>%
  colMeans() %>%
  as.data.frame() %>%
  rownames_to_column("variable") %>%
  mutate(
    k = str_extract(variable, "\\[[0-9]+"),
    k = as.integer(str_remove(k, "\\[")),
    n = str_extract(variable, "[0-9]+\\]"),
    n = as.integer(str_remove(n, "\\]"))
  )
colnames(z_post)[2] <- "value"
    
ggplot(z_post) +
  geom_line(aes(n, value)) +
  facet_wrap(~ k)
```

```{r}
z <- as_tibble(t(res$z[[1]])) %>%
  mutate(n = row_number()) %>%
  pivot_longer(-n, names_to = "k")

ggplot(z) +
  geom_line(aes(n, value)) +
  facet_wrap(~ k)
```

