---
title: "Gaussian Latent Transfer Functions"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(cmdstanr)
library(microTF)
set.seed(20230215)
theme_set(theme_bw())
```


```{r}
n_timepoints <- 100
n_interventions <- 4

interventions <- matrix(0, n_interventions, n_timepoints)
interventions[1, c(10:40)] <- 1
interventions[2, c(50:70)] <- 1
interventions[3, c(50:60)] <- 1
interventions[4, c(80:90)] <- 1

truth <- gaussian_latent_ensemble(interventions, 2, sigma_a = 0.4, sigma_b = 0.4, sigma_e = 0.1, sigma_z = 0.2, P = 2, Q = 2)
plot(truth$x[[1]]@values[1, ])
plot(truth$x[[1]]@values[2, ])
plot(truth$z[[1]][1, ])
plot(truth$z[[1]][2, ])

heatmap(truth$x[[1]]@values)
heatmap(truth$x[[2]]@values)
```

```{r}
hyper <- list(P = 2, Q = 2, K = 3)
fit <- train(truth$x[1], "gaussian_latent", hyper)@parameters
```

```{r}
z_post <- posterior_means(fit$draws("z"), c("k", "n"))
ggplot(z_post) +
  geom_line(aes(n, mean)) +
  facet_wrap(~ k)
```

```{r}
z <- as_tibble(t(truth$z[[1]])) %>%
  mutate(n = row_number()) %>%
  pivot_longer(-n, names_to = "k")

ggplot(z) +
  geom_line(aes(n, value)) +
  facet_wrap(~ k)
```

```{r}
x_obs <- truth$x[[2]][, 1:50]
future_interventions <- truth$x[[2]][, 51:100]@interventions
preds <- gaussian_latent_predict(x_obs, future_interventions, fit)
```

```{r}
preds_long <- preds$x %>%
  map(~ as_tibble(.) %>% mutate(taxon = row_number())) %>%
  bind_rows(.id = "draw") %>%
  pivot_longer(starts_with("V"), names_to = "time") %>%
  mutate(type = "prediction")
```

```{r}
preds_compare <- truth$x[[2]][, 51:100]@values %>%
  as_tibble() %>%
  mutate(taxon = row_number(), type = "truth", draw = "0") %>%
  pivot_longer(starts_with("V"), names_to = "time") %>%
  bind_rows(preds_long) %>%
  mutate(
    time = as.numeric(str_remove(time, "V")),
    draw = as.numeric(draw)
  ) %>%
  filter(taxon < 10, draw < 50)
```

The predictions are reasonably good on short time horizon, but they deteriorate
when trying to extrapolate too far out (e.g., more than 20 steps into the
future).

```{r}
ggplot(preds_compare, aes(time, value)) +
  geom_line(aes(group = draw), col = "#2E0259", size = 0.2, alpha = 0.5) +
  geom_line(
    data = preds_compare %>% filter(type == "truth"),
    aes(group = draw), size = 2, col = "#F2B3D6"
  ) +
  facet_wrap(~ reorder(taxon, value, sd))
```
