---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
library(tfPaper)
library(mbtransfer)
library(patchwork)
library(tidyverse)
library(fs)
library(tidymodels)
theme_set(my_theme())
```

```{r}
ts_list <- list(
  diet = readRDS("../data/ts-diet.rds"),
  postpartum = readRDS("../data/ts-postpartium.rds"),
  aqua = readRDS("../data/ts-aqua.rds")
)
```

```{r}
ts_df <- map(ts_list, pivot_ts)

interventions <- map(ts_list, ~ t(do.call(cbind, map(., \(x) interventions(x))))) |>
  map(~ data.frame(.) |> rownames_to_column("sample"))

ts_df <- map2(ts_df, interventions, ~ left_join(.x, .y))
```

```{r}
library(glue)

composition_plot <- function(ts_df, width = 1, ymax = 1, n_taxa = 10, ylab = "Intervention", title = "") {
  if (n_taxa == 10) {
    pal <- c("#F2668B", "#4C3959", "#2198A6", "#17BFBF", "#F2C777", "#A577A6", "#BF3C1F", "#75A644", "#D99C52", "#69BF97")
  }
  ts1 <- ts_df |>
    group_by(sample) |>
    mutate(prop = value / sum(value))

  top_taxa <- ts1 |>
    group_by(taxon) |>
    summarise(totals = sum(prop)) |>
    arrange(-totals) |>
    pull(taxon)
  
  p1 <- ts1 |>
    filter(taxon %in% top_taxa[seq_len(n_taxa)]) |>
    ggplot() +
    geom_col(aes(time, prop, fill = reorder(taxon, prop), col = reorder(taxon, prop)), width = width) +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0), limits = c(0, ymax)) +
    facet_grid(. ~ subject, scales = "free_x", space = "free_x") +
    theme(
      panel.background = element_rect(fill = "#F2F2F2"),
      panel.grid = element_blank(),
      legend.position = "bottom",
      axis.text.x = element_blank(),
      axis.title.x = element_blank(),
      strip.text = element_text(size = 16),
      title = element_text(size = 20)
    ) +
    labs(y = "Composition", fill = "", col = "", title = title) +
    scale_fill_manual(values = pal) +
    scale_color_manual(values = pal)
  
  p2 <- ts1 |>
    ggplot() +
    facet_grid(. ~ subject) +
    geom_line(aes(time, intervention)) +
    scale_y_continuous(n.breaks = 3) +
    labs(x = "Time", y = ylab) +
    theme(
      strip.text = element_blank()
    )
  
  (p1 / p2) +
    plot_layout(heights = c(0.8, 0.2), guides = "collect")
}
```


```{r, fig.width = 16, fig.height = 8}
p1 <- ts_df[[1]] |>
  filter(subject %in% glue("Animal2")) |>
  rename("intervention" = "Animal") |>
  composition_plot(ymax = 0.42, ylab = "Animal Diet", title = "(a)")

p2 <- ts_df[[2]] |>
  filter(subject %in% c("S10004")) |>
  rename("intervention" = "birth") |>
  composition_plot(width = 14, ymax = 0.55, ylab = "Birth Period", title = "(b)")

p3 <- ts_df[[3]] |>
  filter(subject %in% c("T1")) |>
  rename("intervention" = "pH") |>
  composition_plot(width = 1, ymax = 0.26, ylab = "pH", title = "(c)")
```


```{r, fig.width = 18, fig.height = 5}
p1 | p2 | p3
ggsave("~/Downloads/motivation.png", dpi = 200, width = 18, height = 5)
```

