---
title: "Untitled"
output: html_document
params:
  root_dir: "~/Desktop/collaborations/microbiome_transfer_data/post/data/"
date: "`r Sys.Date()`"
---

```{r}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
library(fs)
library(tidyverse)
library(mbtransfer)
library(glue)
library(tfPaper)
theme_set(my_theme())
```

```{r}
root_dir <- path(params$root_dir)
load(root_dir / "data_post.RData")
```

```{r}
post.df <- post.df |>
  filter(PregOut != "Miscarriage", MonVsDel %in% -7:13, LibrarySize >= 4e4) |>
  group_by(SubjID) |>
  filter(
    max(DayVsDel) > 4, 
    n() > 20
  )

samples <- post.df |>
  rename(sample = SampleID, time = DayVsDel) |>
  mutate(
    condition = time > 0,
    subject = glue("S{SubjID}"),
    BirthControlYesNo = fct_na_value_to_level(BirthControlYesNo, level = "missing")
  ) |>
  ungroup() |>
  select(-SubjID)

reads <- post.df |>
  ungroup() |>
  select(SampleID, LibrarySize, Lactobacillus:L.other) |>
  column_to_rownames("SampleID") |>
  mutate(across(Lactobacillus:L.other, ~ LibrarySize * .)) |>
  select(-LibrarySize)
  
subject_data <- post.df |>
  select(SubjID, HistoryPreterm, Race, Ethnicity, BmiPre, BirthControlYesNo) |>
  ungroup() |>
  mutate(
    bmi_cut = cut(BmiPre, breaks = quantile(BmiPre, seq(0, 1, length.out = 4))),
    subject = glue("S{SubjID}"),
    BirthControlYesNo = fct_na_value_to_level(BirthControlYesNo, level = "missing")
  ) |>
  select(-SubjID) |>
  group_by(subject) |>
  filter(row_number() == 1)

interventions <- samples |>
  mutate(birth = 1 * (time > -14 & time < 0)) |>
  ungroup() |>
  select(sample, birth) |>
  column_to_rownames("sample")
```

```{r}
samples |>
  left_join(interventions |> rownames_to_column("sample")) |>
  ggplot() +
  geom_point(aes(time, subject, col = birth))
```

```{r}
metadata  <- samples |>
  ungroup() |>
  select(sample, condition, AgeDel, BmiPre, BirthControlYesNo, PriorParity)

save(metadata, reads, samples, subject_data, interventions, file = "~/Downloads/postpartum_setup.rda")

ts <- reads |>
 normalize("DESeq2-asinh", metadata) |>
 ts_from_dfs(interventions, samples, subject_data) |>
 interpolate(delta = 14, method = "linear")
```

```{r, fig.height = 12, fig.width = 6}
interaction_barcode(values_df, taxa, "BirthControlYesNo", width = 14)
interaction_barcode(values_df, taxa, "bmi_cut", width = 14)
```

```{r}
tr_fun <- function(x) {
  mbtransfer(x, P = 3, Q = 3)
}

subject_data(ts) <- subject_data(ts) |>
  select(subject, BirthControlYesNo) |>
  mutate(
    BCYes = 1 * (BirthControlYesNo == "Yes"),
    BCNo = 1 * (BirthControlYesNo == "No")
  ) |>
  select(subject, starts_with("BC"))

fit <- tr_fun(ts)
```

```{r}
ws <- steps(c("birth" = TRUE), lengths = 2:4, L = 4)
staxa <- select_taxa(ts, ws[[1]], ws[[2]], tr_fun, n_splits = 20)
```

```{r, fig.height = 10, fig.width = 8}
staxa$ms |>
  mutate(
    taxon = taxa(ts)[taxon],
    lag = as.factor(lag),
    selected = ifelse(taxon %in% unlist(staxa$taxa), "Selected", "Not Selected")
  ) |>
  ggplot() +
  geom_hline(yintercept = 0, size = 2, col = "#d3d3d3") +
  geom_boxplot(aes(reorder(taxon, -m), m, fill = lag, col = lag), alpha = 0.8) +
  facet_grid(. ~ selected, scales = "free_x", space = "free_x") +
  scale_fill_manual(values = c("#c6dbef", "#6baed6", "#2171b5", "#084594")) +
  scale_color_manual(values = c("#c6dbef", "#6baed6", "#2171b5", "#084594")) +
  labs(y = expression(M[j]), x = "Taxon") +
  theme(axis.text.x = element_text(angle = 90, size = 11))

#ggsave("~/Downloads/postpartum-mirror.png", height = 5, width = 10)
```

```{r}
ws <- steps(c("birth" = TRUE), lengths = 2, L = 10)
start_ix <- map_dbl(ts, ~ min(which(.@time >= -14))) - 1

sim_bc <- list()
for (i in 0:1) {
  bc <- subject_data(ts) |>
    mutate(BCYes = rep(i, n()), BCNo = rep(1 - i, n()))
  sim_bc[[i + 1]] <- counterfactual_ts(ts, ws[[1]], ws[[2]], start_ix) |>
    map(~ replace_subject(., bc)) |>
    map(~ predict(fit, .))
}
```

```{r}
focus_taxa <- c("Porphyromonas", "Lactobacillus", "Prevotella_6", "L.gasseri", "L.iners", "Atopobium")
rdata <- sim_bc |>
  map_dfr(~ ribbon_data(.[[2]], .[[1]], focus_taxa, delta =  7), .id = "BC") |>
  mutate(
    BC = fct_recode(BC, No = "1", Yes = "2")
    ) |>
  filter(time > -25, time < 80)

pal <- c("#F2785C", "#144673")
ribbon_plot(rdata, group = "BC") +
  facet_wrap(~ reorder(taxon, median)) +
  labs(y = expression(paste(Delta, " Abundance")), x = "Day", fill = "Birth Control Reinitiated", col = "Birth Control Reinitiated") +
  scale_color_manual(values = pal) +
  scale_fill_manual(values = pal) +
  theme(
    axis.title = element_text(size = 12), 
    strip.text = element_text(size = 12)
  )

#ggsave("~/Desktop/laboratory/talks/2023/20230414/figures/counterfactual_postpartum_staxa.png", width = 9, height = 4.5)
```

```{r}
ts_missing <- subset_values(ts, 1:6)
ts_hat <- predict(fit, ts_missing)
subject_errors <- map_dfr(ts_hat - ts, ~ tibble(mse = mean(abs(values(.)))), .id = "subject")
```

```{r, fig.height = 6, fig.width = 10}
quantiles <- quantile(subject_errors$mse, c(0.1, 0.9))
values_df |>
  left_join(subject_errors) |>
  filter(taxon %in% focus_taxa, mse > quantiles[2] | mse < quantiles[1]) |>
  mutate(
    low_error = ifelse(mse < quantiles[1], "Small Residual", "Large Residual"),
    low_error = factor(low_error, levels = c("Small Residual", "Large Residual")),
    taxon = factor(taxon, levels = focus_taxa)
    ) |>
  ggplot() +
  geom_vline(xintercept = 0, col = "#d3d3d3", size = 2) +
  geom_line(aes(time, value, group = subject), alpha = 0.7, size = 0.4) +
  facet_grid(reorder(taxon, -value) ~ low_error, scales = "free") +
  scale_x_continuous(expand = c(0, 0)) +
  labs(y = "Abundance") +
  theme(
    strip.text.y = element_text(angle = 0, size = 12),
    strip.text.x = element_text(size = 12),
    axis.text = element_text(size = 8)
  )
#ggsave("~/Desktop/laboratory/talks/2023/20230414/figures/residual_postpartum.png", width = 10, height = 6)
```

```{r, fig.width = 10, fig.height = 5}
values_df <- pivot_ts(ts) |>
  group_by(taxon) |>
  mutate(value = rank(value) / n()) |>
  left_join(subject_data)

vis_taxa <- c("Lactobacillus", "L.iners", "Porphyromonas", "Prevotella_6")
interaction_hm(values_df, vis_taxa, "BirthControlYesNo", -1, width = 14) +
  theme(
    axis.text.y = element_blank(),
    strip.text = element_text(size = 12)
  )
ggsave("~/Desktop/laboratory/talks/2023/20230414/figures/progressive_disclosure_postpartum.png", width = 10, height = 4.5)
```