---
title: "simulation"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(microTF)
library(tidyverse)
library(MCMCpack)
library(fs)
source("../microTF/R/simulate_dynamics.R")
theme_set(theme_bw())
set.seed(20230313)
```

This generates the coefficient matrices for dynamics, perturbations, and
interactions.

```{r}
n_lag <- 5
n_taxa <- 50
n_perturb <- 1
n_latent <- 2
n_covariates <- 3

A <- low_rank_step(n_taxa, n_latent, n_taxa, n_lag) %>%
  sparsify() %>%
  normalize(0.5)
B <- low_rank_step(n_taxa, n_latent, n_perturb, n_lag, sigma = 3) %>%
  sparsify(0.5) %>%
  normalize(5)
C <- low_rank_step_(n_taxa, n_latent, n_perturb, n_lag)
for (i in seq_along(C)) {
  C[[i]] <- C[[i]] %>%
    sparsify() %>%
    normalize(0.2)
}
```

Now we can simulate one example series.

For negative binomial simulation, remember that if the variance is $\mu$, the
variance is $\mu + \frac{1}{\text{size}}\mu^2$, where $\text{size}$ is the
number of successes before we stop.

```{r}
step_generator <- step_t(linear_sum(A), linear_sum(B), interaction_sum(C))
x0 <- matrix(2, n_taxa, n_lag + 1)
w <- matrix(0, n_perturb, 50)
w[, 20:25] <- 1
z <- rnorm(n_covariates)
#x <- generate_sample(x0, w, z, step_generator, gaussian_sampler(1))
sizes <- runif(n_taxa, .1, 10)
baselines <- rgamma(n_taxa, 1, .1)
x <- generate_sample(x0, w, z, step_generator, nbinom_sampler(sizes, baselines))
```

Next, we can plot the series.

```{r}
rownames(x) <- str_c("tax", seq_len(nrow(x)))
x_df <- data.frame(x) %>%
  rownames_to_column("taxon") %>%
  pivot_longer(-taxon, names_to = "time") %>%
  mutate(time = as.integer(str_remove(time, "X"))) %>%
  filter(time > 5)

B_df <- map_dfr(
  B, ~ as_tibble(.) %>% 
    mutate(
      taxon = str_c("tax", row_number())
      ) %>%
    rename(B = V1),
  .id = "lag") %>%
  pivot_wider(names_from = "lag", values_from = "B")

x_df <- x_df %>%
  left_join(B_df) %>%
  mutate(effect = rowSums(.[, -c(1:3)]))
  
x_df %>%
  filter(effect < 0) %>%
  ggplot() +
  geom_rect(xmin = 20, xmax = 25, ymin = 0, ymax = max(x_df$value), fill = "#d3d3d3") +
  geom_line(aes(time, value, col = effect)) +
  facet_wrap(~ reorder(taxon, effect)) +
  scale_y_log10() +
  scale_color_gradient2(mid = "#d3d3d3")
```

```{r}
x_df %>%
  filter(effect > 0) %>%
  ggplot() +
  geom_rect(xmin = 20, xmax = 25, ymin = 0, ymax = max(x_df$value), fill = "#d3d3d3") +
  geom_line(aes(time, value, col = effect)) +
  facet_wrap(~ reorder(taxon, effect)) +
  scale_y_log10() +
  scale_color_gradient2(mid = "#d3d3d3")
```

If we were using DESeq2, how would we test?

```{r}

```

