---
title: "Dynamical System Simulation"
output: 
  html_document:
    highlight: "kate"
date: "`r Sys.Date()`"
params:
  run_id: 8
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```
```{r}
library(stringr)
library(glue)
library(tidygraph)
library(tidyverse)
library(tfPaper)
set.seed(params$replicate)
```

```{r}
data_parameters()
```

```{r}
attach(fixed_parameters())
attach(as.list(data_parameters()[params$run, ]))
nonnull_taxa <- list(list(marginal = seq(n_taxa * prop_nonnull)))
nonnull_taxa[[1]]$interaction <- sample(nonnull_taxa[[1]]$marginal, n_taxa * prop_nonnull * prop_interaction)
```

This generates the coefficient matrices for dynamics, perturbations, and
interactions.

```{r}
A <- low_rank_step(n_taxa, n_latent, n_taxa, n_lag) |>
 sparsify(sparsity_A) |>
 normalize_mat(normalizer_A)
B <- random_step(n_taxa, n_perturb, n_lag, lower = signal_B, upper = 2 * signal_B) |>
  sparsify_rows(nonnull_taxa[[1]]$marginal)
C <- random_step(n_taxa, n_perturb, n_lag, lower = signal_C, upper = 2 * signal_C) |>
  sparsify_rows(nonnull_taxa[[1]]$interaction)
```

The definition of which taxa are null varies depending on the lag of the
intervention. An immediate effect on species $i$ may propagate to a lagged-term
effect on species $j$ if there is a nonzero entry in $A_{ij}$.

```{r}
Sigma <- tree_covariance(n_taxa, phylo_alpha, 1)
noise_model <- \() matnorm(1, n_taxa, Sigma = Sigma)
step_generator <- step_t(linear_sum(A), linear_sum(B), interaction_sum(C), noise_model)
theta0 <- matrix(2, n_taxa, n_lag + 1)
w <- random_interventions(n_perturb, n_time, n_subject, n_lag)
z <- matnorm(n_subject, n_covariates)

sizes <- runif(n_taxa, 1, 5)
baselines <- rgamma(n_taxa, 10 * baseline_lambda, baseline_lambda)
x <- generate_samples(step_generator, nbinom_sampler(sizes, baselines), theta0, w, z)
```

### Postprocess

```{r}
w_df <- map_dfr(w, ~ as_tibble(.), .id = "subject") |>
  pivot_longer(-subject, names_to = "time", values_to = "w") |>
  mutate(
    time = as.integer(str_remove(time, "V")),
    value = w,
    sample = str_c("sam", row_number())
  )
```

```{r}
for (i in seq_along(x)) {
  x[[i]] <- x[[i]][, -seq_len(n_lag)]
}

reads <- do.call(cbind, x)
reads[reads > .Machine$integer.max] <- .Machine$integer.max - 1

colnames(reads) <- w_df |>
  filter(time > n_lag) |>
  pull(sample)
reads <- t(reads)
```

```{r}
subject_data <- z |>
  as_tibble() |>
  mutate(subject = as.character(glue("S{row_number()}")))

metadata <- expand.grid(
    time = seq_len(n_time),
    subject = as.character(glue("S{seq_len(n_subject)}"))
  ) |>
  mutate(sample = as.character(glue("sam{row_number()}"))) |>
  filter(time > n_lag) |>
  mutate(time = time - n_time / 2)

interventions <- w_df |>
  filter(time > n_lag) |>
  pull(w, sample) |>
  as.matrix()
colnames(interventions) <- str_c("P", seq_len(n_perturb))
```
```{r}
taxa_ids <- c(str_c("internal", seq_len(n_taxa)), rownames(x[[1]]))
taxonomy <- create_tree(2 * n_taxa + 1, 2) |>
  activate(edges) |>
  mutate(
    tax_name = taxa_ids[to], 
    name = tax_name,
    kingdom = "bacteria",
    phylum = NA,
    sequence = NA,
    class = NA,
    order = NA,
    family = NA,
    genus = NA,
    species = NA
  ) |>
  as_tibble() |>
  rename(tax_id = to, parent_id = from) |>
  filter(!str_detect(tax_name, "internal")) |>
  select(tax_id, parent_id, everything())
```

```{r}
save(reads, Sigma, interventions, metadata, subject_data, taxonomy, nonnull_taxa, file = output_path)
```

```{r, eval = FALSE, fig.width = 8, fig.height = 4}
values_df <- data.frame(reads) |>
  rownames_to_column("sample") |>
  pivot_longer(-sample, names_to = "taxon") |>
  filter(taxon %in% str_c("tax", c(1:3, 40, 38, 50))) |>
  left_join(metadata) |>
  group_by(taxon) |>
  mutate(value = rank(value) / n()) |>
  left_join(rownames_to_column(data.frame(interventions), "sample"))
  
ggplot(values_df, aes(time, reorder(subject, value))) +
  geom_tile(aes(fill = value, col = as.factor(P1), size = P1)) +
  facet_wrap(~ taxon) +
  labs(x = "Time", y = "Subject", fill = "Quantile") +
  scale_fill_gradient(low = "#eaf7f7", high = "#037F8C") +
  scale_color_manual(values = c("#F2E8DF", "#BF3945"), guide = FALSE) +
  scale_size(range = c(0, .25), guide = FALSE) +
  scale_x_continuous(expand = c(0, 0)) +
  theme(
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank()
  )

ggsave("simulation-hm.png", width = 8, height = 4, dpi = 1000)
```

```{r, eval = FALSE}
for (i in seq_len(243)){
  if (i %% 5 == 0) {
    print(glue::glue("{i}/243"))
  }
  rmarkdown::render("simulation_data.Rmd", params = list(run_id = i), quiet = TRUE)
}
```
