---
title: "Untitled"
output: 
  html_document:
    highlight: "kate"
params:
  outputs_dir: "../data/simulation_output/"
  outputs_filter: "*rda"
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(glue)
library(fs)
library(tidyverse)
library(tfPaper)
theme_set(my_theme())
```

```{r}
data_var <- data_parameters(params$outputs_dir) |>
  mutate(data_path = factor(output_path)) |>
  select(-output_path)
configurations <- method_configurations(data_var$data_path) |>
  left_join(data_var)
```

```{r}
paths <- dir_ls(params$outputs_dir, recurse = TRUE) |>
  path_filter(regexp=params$outputs_filter)

metadata <- paths |>
  as_tibble() |>
  mutate(output_path = basename(value)) |>
  rename(full_path = value) |>
  left_join(configurations)
```

## Forecasting Results
```{r}
metrics <- paths |>
  path_filter("*forecasting*") |>
  map_dfr(~ { load(.); metrics }, .id = "full_path")

computation <- paths |>
  path_filter("*forecasting*") |>
  map_dfr(~ { load(.); tibble(time_diff = time_diff) }, .id = "full_path")
```

```{r}
computation |>
  left_join(metadata) |>
  unnest_wider(hyper) |>
  mutate(
    time_diff = as.numeric(time_diff) / 60,
    P = ifelse(is.na(P), "", as.character(P)),
  ) |>
  ggplot() +
  geom_boxplot(aes(normalization, time_diff, col = interaction(method, P), fill = interaction(method, P)), alpha = 0.6) +
  scale_fill_brewer(palette = "Set1") +
  scale_color_brewer(palette = "Set1") +
  scale_y_log10() +
  labs(y = "Minutes", col = "Method", fill = "Method") +
  facet_wrap(~ method) +
  theme(strip.text = element_text(size = 16))
ggsave("~/Desktop/laboratory/talks/2023/20230414/figures/computation-sim.png", width = 8, height = 4)
```

```{r, fig.width = 12, fig.height = 6}
metrics <- metrics |>
  left_join(metadata) |>
  unnest_wider("hyper")

metrics |>
  mutate(
    n_taxa = glue("{n_taxa} taxa"),
    prop_nonnull = glue("{100 * prop_nonnull}% nonnull"),
    P = ifelse(is.na(P), "", as.character(P)),
    signal_B = glue("b = {signal_B}")
  ) |>
  ggplot() +
  geom_boxplot(aes(normalization, mae, fill = interaction(factor(method), P), col = interaction(factor(method), P)), alpha = 0.5) +
  scale_fill_brewer(palette = "Set1") +
  scale_color_brewer(palette = "Set1") +
  facet_wrap(prop_nonnull ~ signal_B) +
  labs(x = "Normalization", y = "Mean Absolute Error (H = 1,..,5)", col = "Method", fill = "Method", title = "50 Taxa") +
  scale_y_sqrt(limits = c(0, 500)) +
  theme(
    strip.text = element_text(size = 14),
    legend.title = element_text(size = 16),
    legend.text = element_text(size = 14),
    title = element_text(size = 20)
  )
#ggsave("~/Desktop/laboratory/talks/2023/20230414/figures/forecasting-sim-error.png", height = 6, width = 12)
```

### Inferential Results

```{r}
inference_config <- configurations |>
  filter(map_lgl(hyper, ~ !is.null(.$P) > 0 && .$P == 2)) |>
  mutate(output_path = glue("inference-{str_pad(row_number(), 3, 'left', '0')}.rda")) |>
  select(-method)

testing_results <- paths |>
  path_filter("*inference*") |>
  map_dfr(~ { load(.); testing_results }, .id = "full_path") |>
  mutate(output_path = path_file(full_path)) |>
  left_join(inference_config)
```

```{r, fig.height = 7, fig.width = 10}
pal <- c("#c6dbef", "#6baed6", "#2171b5", "#084594")
testing_results |>
  filter(type == "marginal") |>
  mutate(
    prop_nonnull = glue("{100 * prop_nonnull}% nonnull"),
    signal_B = glue("b = {signal_B}")
  ) |>
  ggplot() +
  geom_vline(xintercept = 0.2, col = "#898989", size = 1) +
  geom_point(aes(fdp, power, shape = signal_B, col = lag), size = 3) +
  scale_color_manual(values = pal) +
  facet_grid(n_taxa + normalization ~ method + prop_nonnull) +
  labs(x = "False Discovery Proportion", y = "Power", col = "Lag") +
  theme(
    axis.text = element_text(size = 10),
    strip.text = element_text(size = 14),
    strip.text.y = element_text(angle = 0, size = 14),
    panel.spacing = unit(0.1, "line")
  )

ggsave("inference-sim-error.png", height = 5, width = 10)

summary_table <- testing_results |>
  filter(type == "marginal") |>
  group_by(method, normalization, lag, n_taxa, prop_nonnull, signal_B) |>
  summarise(
    FDP = round(mean(fdp), 3),
    FDP_sd = round(sd(fdp), 3)
  )

write_csv(summary_table, "summary_table_fdp.csv")
```
```{r}
summary_table
```
```{r}
testing_results |>
  filter(type == "marginal", str_detect(full_path, "inference-129.rda")) |>
  select(method, normalization, lag, fdp)
```

