---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```
```{r}
library(microTF)
library(tidyverse)
library(tidymodels)
```


```{r}
interventions <- matrix(0, 1, 100)
interventions[1, 50] <- 1
sigma_z <- 0
sigma_e <- 0
L <- matrix(1, 1, 1)
A <- list(matrix(0.8, 1, 1))
B <- list(matrix(0, 1, 1), matrix(0, 1, 1), matrix(0.8, 1, 1))
params <- list(A = A, B = B, L = L)
```

```{r}
result <- gaussian_latent(interventions, params, sigma_z, sigma_e)
plot(result$z[1, ])
plot(result$x[1, ])
```

```{r}
sigma_z <- 0.05
sigma_e <- 0

result <- gaussian_latent(interventions, params, sigma_z, sigma_e)
plot(result$z[1, ])
plot(result$x[1, ])
```

```{r}
sigma_z <- 0
sigma_e <- 0.05

result <- gaussian_latent(interventions, params, sigma_z, sigma_e)
plot(result$z[1, ])
plot(result$x[1, ])
```

```{r}
sigma_z <- 0.04
sigma_e <- 0.04
L <- microTF:::sparse_normal(10, 2)
A <- list(matrix(c(0.5, 0.2, 0.2, 0.5), 2, 2))
B <- c(replicate(5, matrix(0, 2, 1), sim = F), list(matrix(c(0.5, 0.5), 2, 1)))
params <- list(A = A, B = B, L = L)

result <- gaussian_latent(interventions, params, sigma_z, sigma_e)
plot(t(result$z))
plot(result$z[1, ])
abline(v = 50)
plot(result$x[1, ])
abline(v = 50)
```

We can also have a more gradual buildup if we allow transfer from several
timepoints at once.

```{r}
B <- c(
  replicate(3, matrix(0, 2, 1), sim = F), 
  replicate(8, matrix(c(0.3, .3), 2, 1), sim = F)
)
params <- list(A = A, B = B, L = L)

result <- gaussian_latent(interventions, params, sigma_z, sigma_e)
plot(t(result$z))
plot(result$z[1, ])
abline(v = 50)
plot(result$x[1, ])
abline(v = 50)
```

```{r}
L <- microTF:::sparse_normal(50, 2)
params <- list(A = A, B = B, L = L)
result <- gaussian_latent(interventions, params, sigma_z, sigma_e)
result_df <- as_tibble(result$x) %>%
  mutate(taxon = row_number()) %>%
  pivot_longer(-taxon, names_to = "time") %>%
  mutate(time = as.integer(str_remove(time, "V"))) %>%
  pivot_wider(names_from = taxon, values_from = value)

pca_rec <- recipe(~ ., data = result_df) %>%
  update_role(time, new_role = "id") %>%
  step_pca(all_predictors())

pca_result <- prep(pca_rec)
  
theme_set(theme_bw())
ggplot(bake(pca_result, result_df)) +
  geom_point(aes(PC1, PC2, col = time)) +
  scale_color_steps2(midpoint = 50, breaks = seq(0, 100, 10), mid = "#bfbfbf") 
```

```{r}
L_hat <- tidy(pca_result, 1) %>%
  filter(component %in% str_c("PC", 1:2)) %>%
  pivot_wider(names_from = component, values_from = value) %>%
  bind_cols(L = as.data.frame(L))
colnames(L_hat)[5:6] <- c("L1", "L2")

ggplot(L_hat) +
  geom_point(aes(PC1, L1))
ggplot(L_hat) +
  geom_point(aes(PC2, L2))
```
