---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```
```{r}
library(microTF)
library(tidyverse)
library(gbm)
theme_set(theme_bw())
```

```{r}
n_subjects <- 100
n_timepoints <- 50
interventions <- matrix(0, 1, n_timepoints)
L <- microTF:::sparse_normal(5, 1, s = 0)
A <- list(matrix(0.8, 1, 1))
B <- list(matrix(0, 1, 1), matrix(0, 1, 1), matrix(0.8, 1, 1))
params <- list(A = A, B = B, L = L)

series <- list()
for (i in seq_len(n_subjects)) {
  interventions_ <- interventions
  interventions_[1, sample(n_timepoints - 4, 2)] <- 1
  sim <- gaussian_latent(interventions_, params, 0, 0.05)
  series[[i]] <- new(
    "ts_inter_single", 
    values = sim$x,
    time = seq_len(ncol(interventions)),
    interventions = interventions_
  )
}

result <- new("ts_inter", series = series)
```

```{r}
for (i in seq_len(5)) {
  plot(values(result[[i]])[1, ])
}
```


```{r}
fit <- train(result, method = "gbm")

train_data <- patchify_df(result, p = 1, q = 4)
y_hat <- predict(fit@parameters[[1]], train_data$x)
plot(train_data$y[[1]], y_hat)
abline(a = 0, b = 1, col = "red")
```

Get predictions for all taxa in future interventions. Cannot compare with truth,
since no holdout. First 25 timepoints are observed, the next 10 are forecast.

```{r}
new_interventions <- matrix(c(0, 0, 0, 1, 1, 0, 0, 0, 0, 0), nrow = 1)
y_hat <- gbm_predict_(fit@parameters, result, new_interventions)
plot(values(y_hat[[2]])[1, ])
```

Let's next consider actually holding out some examples and looking at
predictions.


```{r}
K <- 5
splits <- train_test_split(result, 1 / K)
fit <- train(splits$train, "gbm")
```

```{r}
t_start <- 30
n_ahead <- 20

# hide the second half of each test sample
stest <- splits$test
new_interventions <- list()
for (i in seq_along(splits$test)) {
  values(stest[[i]]) <- values(stest[[i]])[, seq_len(t_start), drop = FALSE]
}

y_hat <- predict(fit, stest)
```

```{r}
compare_data <- list()
for (i in seq_along(y_hat)) {
  compare_data[[i]] <- tibble(
    time = seq_len(ncol(y_hat[[i]])),
    subject = i
  ) %>%
    bind_cols(
      as_tibble(t(values(y_hat[[i]]))) %>%
        set_names(str_c("y_hat", seq_len(nrow(y_hat[[i]]))))
    ) %>%
    bind_cols(
      as_tibble(t(values(splits$test[[i]]))) %>%
        set_names(str_c("y", seq_len(nrow(y_hat[[i]]))))
    ) %>%
    pivot_longer(-c("time", "subject")) %>%
    mutate(
      taxon = str_extract(name, "[0-9]+"),
      type = str_remove(name, "[0-9]+")
    )
}

compare_data <- bind_rows(compare_data) %>%
  filter(!(time <= t_start & type == "y_hat"))
```

```{r, fig.width = 10, fig.height = 10}
ggplot(
  compare_data %>% filter(subject < 10),
  aes(time, value, col = type)
  ) +
  geom_point() +
  geom_line(aes(group = subject)) +
  facet_grid(subject ~ reorder(taxon, value), scales = "free_y") +
  scale_color_manual(values = c("#5C51A6", "#8C1C03"))
```

```{r}
ggplot(compare_data) +
  geom_tile(aes(time, reorder(subject, value), fill = value)) +
  facet_grid(reorder(taxon, value) ~ type) +
  scale_fill_gradient2() +
  scale_x_continuous(expand = c(0, 0), limits = c(30, 50))
```
