---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(microTF)
```

```{r}
series <- list()
for (i in seq_len(50)) {
  series[[i]] <- new(
    "ts_inter_single", 
    values = matrix(rnorm(20), 2, 10), 
    time = 1:10, 
    interventions = matrix(c(0, 1), 1, 10)
  )
}

obj <- new("ts_inter", series = series)
length(obj)
obj[1:2]
```

Here we manually hold out the last half of the timepoints for half the people
and ask for predictions.

```{r}
fit <- train(obj[1:25])
values(obj[[1]]) <- matrix(rnorm(20), 2, 10)
interventions(obj[[2]]) <- matrix(10:1, 1, 10)

# hide the last half of each test object
test <- obj
for (i in seq(26, 50)) {
  values(test[[i]]) <- values(test[[i]])[, 1:5, drop = F]
}
y_hat <- predict(fit, newdata = test)
```

Alternatively, we can use cross-validation to compute errors across many folds.

```{r}
cross_validate(obj, train)$metrics
```


```{r}
hyper <- list(P = 1, Q = 1, K = 2)
fit <- train(obj[1], "gaussian_latent", hyper)
y_hat <- predict(fit, newdata = test[26])

tr <- function(x) {
  train(x, "gaussian_latent", hyper)
}

#cross_validate(obj, tr)$metrics
```

